USERS_TABLE = 'users'
MOVIES_TABLE = 'movies'
WATCHED_TABLE = 'watched'
SCRAPING_TABLE = 'scraping'

NAME_COLUMN = 'name'
USERS_ID_COLUMN = 'user_id'
MOVIE_ID_COLUMN = 'movie_id'
TITLE_COLUMN = 'title'
ROTTEN_COLUMN = 'rotten'
ALL_COLUMNS = '*'
URL_COLUMN = 'url'
TIME_COLUMN = 'time'

PASSWORD_FILE = './patoNaculudu.txt'
